### ISSUE TITLE
Data release

### ISSUE THREAD

**Issue by jannisborn** [boschresearch/eurekaMoments#1]
Great paper and great repo! To ensure reproducibility could you please release the data as well?

**Comment by DavHoffmann** [comment]
Hi Jannis,

thank you for the kind words. 

The datasets used are the publicly available MNIST and fashion MNIST datasets.
As far as I know we are not allowed to redistribute them, but you can easily download them from the original sources. 

Using these datasets we generate our data on the fly. The code for that can be found in this [script](https://github.com/boschresearch/eurekaMoments/blob/main/datasets.py). 
 
Please let me know in case you need further assistance.

**Comment by jannisborn** [comment]
Thanks David for the fast response! Makes sense you cant share, the script should definitely be enough to reproduce :)

We aim to construct the data for the main task studied in the paper (MNIST vs. FashionMnist with the two colored MNIST images in top left and bottom right). Looks like this means we have to use `spacial_decision_indicator_digit_1_2_fashion` with the defaults (`top_right_probability` is 0.5, `num_colors_per_class=1`. 

Closing this, I'll ping you again in case we run into problems with this. Thanks!
